name: AdService CI

on:
  push:
    branches: [main]
    paths:
      - 'src/adservice/**'
      - '.github/workflows/adservice.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'src/adservice/**'

jobs:
  build-adservice:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-service-template.yaml
    with:
      service-name: adservice
      service-path: src/adservice
      dockerfile: Dockerfile
      k8s-repo: c0dysharma/microservices-demo-k8s
      k8s-values-file: values/ad-service-values.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K8S_REPO_TOKEN: ${{ secrets.K8S_REPO_TOKEN }}
      GH_USER: ${{ secrets.GH_USER }}