name: CartService CI

on:
  push:
    branches: [main]
    paths:
      - 'src/cartservice/**'
      - '.github/workflows/cartservice.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'src/cartservice/**'

jobs:
  build-cartservice:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-service-template.yaml
    with:
      service-name: cartservice
      service-path: src/cartservice
      dockerfile: Dockerfile
      k8s-repo: c0dysharma/microservices-demo-k8s
      k8s-values-file: values/cart-service-values.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K8S_REPO_TOKEN: ${{ secrets.K8S_REPO_TOKEN }}
