name: CartService CI

on:
  push:
    branches: [main]
    paths:
      - 'src/cartservice/**'
      - '.github/workflows/cartservice.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'src/cartservice/**'

jobs:
  build-cartservice:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-service-template.yaml
    with:
      service-name: cartservice
      service-path: src/cartservice
      dockerfile: Dockerfile
      registry: docker.io
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
