name: CheckoutService CI

on:
  push:
    branches: [main]
    paths:
      - 'src/checkoutservice/**'
      - '.github/workflows/checkoutservice.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'src/checkoutservice/**'

jobs:
  build-checkoutservice:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-service-template.yaml
    with:
      service-name: checkoutservice
      service-path: src/checkoutservice
      dockerfile: Dockerfile
      k8s-repo: c0dysharma/microservices-demo-k8s
      k8s-values-file: values/checkout-service-values.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K8S_REPO_TOKEN: ${{ secrets.K8S_REPO_TOKEN }}