name: CurrencyService CI

on:
  push:
    branches: [main]
    paths:
      - 'src/currencyservice/**'
      - '.github/workflows/currencyservice.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'src/currencyservice/**'

jobs:
  build-currencyservice:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-service-template.yaml
    with:
      service-name: currencyservice
      service-path: src/currencyservice
      dockerfile: Dockerfile
      k8s-repo: c0dysharma/microservices-demo-k8s
      k8s-values-file: values/currency-service-values.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K8S_REPO_TOKEN: ${{ secrets.K8S_REPO_TOKEN }}
