name: EmailService CI

on:
  push:
    branches: [main]
    paths:
      - 'src/emailservice/**'
      - '.github/workflows/emailservice.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'src/emailservice/**'

jobs:
  build-emailservice:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-service-template.yaml
    with:
      service-name: emailservice
      service-path: src/emailservice
      dockerfile: Dockerfile
      k8s-repo: c0dysharma/microservices-demo-k8s
      k8s-values-file: values/email-service-values.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K8S_REPO_TOKEN: ${{ secrets.K8S_REPO_TOKEN }}