name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - 'src/frontend/**'
      - '.github/workflows/frontend.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'src/frontend/**'

jobs:
  build-frontend:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-service-template.yaml
    with:
      service-name: frontend
      service-path: src/frontend
      dockerfile: Dockerfile
      registry: docker.io
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
