name: PaymentService CI

on:
  push:
    branches: [main]
    paths:
      - 'src/paymentservice/**'
      - '.github/workflows/paymentservice.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'src/paymentservice/**'

jobs:
  build-paymentservice:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-service-template.yaml
    with:
      service-name: paymentservice
      service-path: src/paymentservice
      dockerfile: Dockerfile
      k8s-repo: c0dysharma/microservices-demo-k8s
      k8s-values-file: values/payment-service-values.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K8S_REPO_TOKEN: ${{ secrets.K8S_REPO_TOKEN }}