name: ProductCatalogService CI

on:
  push:
    branches: [main]
    paths:
      - 'src/productcatalogservice/**'
      - '.github/workflows/productcatalogservice.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'src/productcatalogservice/**'

jobs:
  build-productcatalogservice:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-service-template.yaml
    with:
      service-name: productcatalogservice
      service-path: src/productcatalogservice
      dockerfile: Dockerfile
      k8s-repo: c0dysharma/microservices-demo-k8s
      k8s-values-file: values/productcatalog-service-values.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K8S_REPO_TOKEN: ${{ secrets.K8S_REPO_TOKEN }}
