name: RecommendationService CI

on:
  push:
    branches: [main]
    paths:
      - 'src/recommendationservice/**'
      - '.github/workflows/recommendationservice.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'src/recommendationservice/**'

jobs:
  build-recommendationservice:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-service-template.yaml
    with:
      service-name: recommendationservice
      service-path: src/recommendationservice
      dockerfile: Dockerfile
      k8s-repo: c0dysharma/microservices-demo-k8s
      k8s-values-file: values/recommendation-service-values.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K8S_REPO_TOKEN: ${{ secrets.K8S_REPO_TOKEN }}
