name: ShippingService CI

on:
  push:
    branches: [main]
    paths:
      - 'src/shippingservice/**'
      - '.github/workflows/shippingservice.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'src/shippingservice/**'

jobs:
  build-shippingservice:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-service-template.yaml
    with:
      service-name: shippingservice
      service-path: src/shippingservice
      dockerfile: Dockerfile
      k8s-repo: c0dysharma/microservices-demo-k8s
      k8s-values-file: values/shipping-service-values.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K8S_REPO_TOKEN: ${{ secrets.K8S_REPO_TOKEN }}
